version: 2

sources:
  - name: olist
    schema: main
    tables:
      - name: raw_customers
      - name: raw_orders
      - name: raw_order_items
      - name: raw_payments
      - name: raw_reviews
      - name: raw_products
      - name: raw_sellers
      - name: raw_geolocation
      - name: raw_product_category_translation
